### ISSUE TITLE
🐛 BUG: SyntaxError when using components to wrap children

### ISSUE THREAD

**Issue by jungaretti** [snowpackjs/astro#1757]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Astro reports `SyntaxError: [75:172]: Expected ')'` when I use a base components to wrap child components. This prevents me from using a generic `Base` component for common HTML code.

### Steps to Reproduce

`Base.astro` is a component for with everything shared among my components:

```astro
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width" />
	<title>Welcome to Astro</title>
</head>
<body>
    <span />
</body>
</html>
```

`index.astro` uses `Base` to wrap its actual content:

```astro
---
import Base from "./components/Base.astro";
---
<Base>
    <h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
</Base>
```

### Link to Minimal Reproducible Example (Optional)

https://github.com/jungaretti/astro-component-syntaxerror

**Comment by natemoo-re** [comment]
This is a known bug with the old compiler. Our compiler has been completely rewritten and is currently released under `astro@next`. We're finishing up a few stability issues but it should be promoted to `latest` in the coming days. 

Going to keep this open until it's released.

**Comment by natemoo-re** [comment]
Following up on my previous comment, the team has decided to close out issues that have been confirmed as fixed by [astro@0.21.0-next.0](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.0), [astro@0.21.0-next.1](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.1), or [astro@0.21.0-next.2](https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0-next.2). Our hope is that this will help the [v0.21 milestone](https://github.com/snowpackjs/astro/milestone/1) remain as actionable as possible.

To verify that this issue has been fixed, you may
- Open a new [`astro@next` project on StackBlitz](https://astro.new/minimal@next)
- Locally upgrade to the `astro@next` preview
    ```shell
    npm i astro@next
    # If using Framework renderers...
    npm i @astrojs/renderer-name@next
    ```

If you think we made a mistake, **please reopen this issue**!

If you run into any other problems with `astro@next`, please [open a new issue](https://github.com/snowpackjs/astro/issues/new?assignees=&labels=0.21&template=---01-bug-report.yml&title=%F0%9F%90%9B+BUG%3Aastro@next).

**Comment by jungaretti** [comment]
This is still broken: `RuntimeError: Error: Uh oh, the Astro compiler encountered an unrecoverable error!`

I updated my example repo to `astro@0.21.5`. Notice that removing references to `Base` fixes the issue: https://github.com/jungaretti/astro-component-syntaxerror

**Comment by jungaretti** [comment]
I'm going to open a new issue
