### ISSUE TITLE
🐛 BUG: Node builtins can't be imported in `astro@next`

### ISSUE THREAD

**Issue by Princesseuh** [snowpackjs/astro#1769]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

In the current latest version, node builtins can be imported by using the `node:` prefix, however this doesn't work in `astro@next`. The normal syntax without the prefix also doesn't work

### Steps to Reproduce

1. Try to import a node builtin, ex: `import { readFile } from "node:fs/promises"`
2. Run project in dev mode
3. You'll get a 500 error with the following content `Failed to resolve import "node:fs/promises"`

**Comment by aFuzzyBear** [comment]
This issue, is also reproduced on a `yarn-wsl2(Ubuntu20.04)` system. It looks like their is **no** access to the `fs` nor `node:builtins` when one looks to import it anywhere in  any file format in Astro. 
```jsx
import fs from { 'node:fs' | 'fs' }
import path from {'node:path' | 'path' }
....
```

I must confess, I especially loved Astro's node builtins. Worked really well in versions `<0.21@next` . I hope this could be reintroduced into Astro,

**Comment by natemoo-re** [comment]
I'd definitely consider this a bug! We'll tackle this ASAP.

**Comment by IanVS** [comment]
FWIW, I was able to `import { promises } from 'fs` using 0.21.0-next.2 in https://codesandbox.io/s/astro-1184-jn9du

**Comment by matthewp** [comment]
@Princesseuh can you speak to what you are doing differently than what is shown above?

**Comment by jasikpark** [comment]
I imagine the idea was to use `import { promises } from 'node:fs';` like in astro@0.20

**Comment by Princesseuh** [comment]
Hmm the specific way the project I first encountered the issue in does it is using the following line:

```js
import { readFile } from "node:fs/promises"
```

Where neither the prefixed syntax or the normal syntax worked (the non promises version didn't work either). The prefixed version worked in 0.20. I'll try the syntax IanVS suggested to see if it works

**Comment by Princesseuh** [comment]
I can confirm that IanVS's syntax does work, not sure why there's a problem with `fs/promises` or aFuzzyBear's exemple 🤔

**Comment by matthewp** [comment]
It could be Node.js version, `fs/promises` started with Node 14 IIRC.

**Comment by Princesseuh** [comment]
I'm using Node 17 so it shouldn't be an issue 😅

**Comment by FredKSchott** [comment]
Fixed in v0.21!

**Comment by RafidMuhymin** [comment]
@FredKSchott I can still reproduce the issue using `fs/promises`

**Comment by IanVS** [comment]
@RafidMuhymin do you have a reproduction that you can share?
