### ISSUE TITLE
🐛 Tailwindcss sometimes does not work

### ISSUE THREAD

**Issue by muhammetsait** [snowpackjs/astro#481]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins (`v0.13.10`).
- [x] I am on an ESM Node.js version (`v16.3.0`)
- [x] I use package manager: (npm `v7.15.1`).
- [x] I run Astro on OS: (Linux, `v5.10.41-1-MANJARO`).

### Describe the bug

Starting with fresh install, install tailwindcss following instructions in Styling guide, `@tailwind` directives in `global.css` don't seem to work, using tailwind in `class` attribute does not work, applying styles using `@apply` *works*.

### Steps to reproduce

Repo: https://github.com/muhammetsait/astrotest

1. clone reproduction repo
2. `npm install`
3. `npm run start`

### Expected behavior

I expect the two buttons to look the same. (Currently styles only apply to the second one)

### More information

I tried deleting the whole folder and cloned the repo again and it worked! Then I made some changes and it stopped working even after I tried undoing what I changed.

Also, `npm run build` fails, the message says `could not find global.css` but that message is misleading, if you change the contents of `global.css` to regular css instead of `@tailwind` directives it would build successfully.

**Comment by muhammetsait** [comment]
I found that removing `<style>` tag completely from `Button2` solves the problem. Also, the issue does not appear again (after adding `style` tag again) unless I restart the command `npm run start`

@drwpow

**Comment by aFuzzyBear** [comment]
I just wanted to add;

After @drwpow suggested to remove the style tags, I ended up removing all the styles tags and the style rules that were in the other css files, `public/styles/{global.css,home.css}` , 
Right now I can only seem to inline the tailwindcss, this bug seems to be known, but I did want to mention that it doesn't seem to work with HMR, in order to view the style changes requires a page refresh...

**Comment by bradlc** [comment]
I added some logs to the `tailwindcss` module to see what Tailwind is receiving from Astro:

```js
{
  from: '{projectRoot}/src/components/Button2.css',
  css: 'button.astro-NqF0dKd1 {\n' +
    '  @apply bg-indigo-700 hover:bg-indigo-900 text-white px-3 py-2 rounded;\n' +
    '}\n'
}
```

```js
{
  from: '{projectRoot}/src/components/Button2.css',
  css: '@tailwind base;\n@tailwind components;\n@tailwind utilities;'
}
```

It looks like there's two issues here:

- For the first one: `from` should be `Button2.astro`, not `Button2.css`. This causes the Tailwind build to fail because `Button2.css` is not an actual file.
- For the second one: `from` shouldn't be `Button2` at all, it should be `{projectRoot}/public/style/global.css`

**Comment by natemoo-re** [comment]
Thanks @bradlc, that's super helpful! I'm sure that's the problem here. We'll work on a fix ASAP.

**Comment by drwpow** [comment]
I believe this has been fixed as of the latest release of Astro. Using the repo provided above, I can update Astro to the latest version and I’m seeing the correct Tailwind styles apply in both button files now, and the `global.css` file also seems to be resolving correctly now as well.

I suspect there may still be some caching / HMR issues in Tailwind, so I’ll leave this ticket open for if you discover any weirdness there.

---

Unrelated, but just a heads up: we’ll be updating our Tailwind docs soon and suggest you move `public/styles/global.css` -> `src/global.css` (or wherever you’d like, e.g. `src/styles/global.css`; doesn’t matter). Then update your HTML:

```diff
- <link href="/styles/global.css" />
+ <link href="/_astro/src/global.css" />
```

(just prefix the path to the file with `/_astro/[path to file]`). The reason for the switch is basically that we’ll make some changes to how the CSS bundling happens and we may stop processing CSS in `public/` altogether (which would include Tailwind). That change will be coming in a future release, but just a heads up now.

**Comment by muhammetsait** [comment]
Unfortunately the issue still exists. The styles _sometimes_ appear correctly when running the dev server, but `build` always fails. Same as old behavior. (tested using Astro 0.13.12 & Tailwind 2.2.2)

**Comment by bradlc** [comment]
Thanks @drwpow. Here's my observations:

* `0.13.12` has the same behaviour as described in the original issue, but I believe this is because this version [reverted](https://github.com/snowpackjs/astro/blob/main/packages/astro/CHANGELOG.md#01312) changes made in `0.13.11`
* `0.13.11` appears to fix the issue in the reproduction repository, but there's still an issue in that the PostCSS `from` option is being set to `Button2.css` instead of `Button2.astro`. This will cause errors in certain situations, for example if you add `@tailwind components;` to the `<style>` in `Button2.astro` you will encounter an error:

```
Error: ENOENT: no such file or directory, stat '{projectRoot}/src/components/Button2.css'
```

**Comment by drwpow** [comment]
Ah hm. I believe I tested `0.13.11`. Will look into that regression.

As for the `from` option, I was actually seeing that set to `Button2.astro` with the latest version on a clean install. I know Tailwind (and possibly PostCSS) keep caches; do you still see the same on a clean install (`git clean -dfx && npm i`)?

**Comment by bradlc** [comment]
> [...] do you still see the same on a clean install (`git clean -dfx && npm i`)?

Yeah

**Comment by drwpow** [comment]
We recently released Astro `0.14.0` which does fix the big problem again for HMR. But I am seeing that `Button2.css` error still as you mentioned. Will look into fixing that. Sorry—I didn’t catch it before because as you mentioned it does only appear in certain situations

**Comment by natemoo-re** [comment]
This should be fixed soon!

@drwpow was able to track this down to a bug hiding in `@snowpack/plugin-postcss`, so there's [a PR out](https://github.com/snowpackjs/snowpack/pull/3483#pullrequestreview-692142514) to fix this upstream.

Basically, Snowpack's PostCSS plugin was passing around a virtual file `id` rather than the real filepath on disk.

**Comment by drwpow** [comment]
@bradlc good news! I think this will be fixed in #538.

**Comment by bradlc** [comment]
Thanks @drwpow! I am still seeing a couple oddities with (Post)CSS handling but I will open new issues for those 👍
