### ISSUE TITLE
🐛 createCollection() hits an error if pageSize is set to Infinity

### ISSUE THREAD

**Issue by tony-navillus** [snowpackjs/astro#483]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v12.20.0+, v14.13.1+, or v16.0.0+`)
- [x] I use package manager: (Fill in: npm, yarn, pnpm, etc).
- [x] I run Astro on OS: (Fill in: Windows, Mac, Linux, etc).

### Describe the bug

I'm creating a collection of blog posts to generate routes for each unique author.  I followed closely to the [collections docs example](https://github.com/snowpackjs/astro/blob/main/docs/collections.md#example-individual-pages-from-a-collection), but when `async data({ params })` is called `params` is an empty object.

The `permalink` call works as expected and is passed `params` for each collection item.

### Steps to reproduce

Demo project hitting the issue can be found [here](https://github.com/Navillus-BV/demo-astro-netlify-cms)

1. clone [Github repo](https://github.com/Navillus-BV/demo-astro-netlify-cms)
2. cd `demo-astro-netlify-cms`
3. npm i && npm run build
4. Error: [createCollection] `data()` returned nothing (empty data)"

Add console logs or debug breakpoints and you'll see the `params` is passed to `permalink`, but in `data()` the `params` passed is an empty object

### Expected behavior

`data({ params })` should include the data for each page 

### Anything else?

Not sure if this is related, when debugging I noticed that `permalinks` and `data` functions seem to be called twice for the same collection.

using node v16.1.0 (npm v7.11.2) on Ubuntu 20.10 (Pop!_OS)

**Comment by FredKSchott** [comment]
Haven't run this yet, but I ran into this with another user and it was because `permalink` was returning a bad URL, something like `/posts/undefined`. Can you add a log to that function to confirm that it's as expected?

**Comment by tony-navillus** [comment]
No problem, just pushed a little extra debug logging to the project repo.  Here's the output right before the build fails, printing `permalink: ${result}` from the `permalink` call before returning the same `result` string

```bash
permalink: /authors/jane-doe
permalink: /authors/john-appleseed
permalink: /authors/john-doe
data() params:  {}
permalink: /authors/jane-doe
permalink: /authors/john-appleseed
permalink: /authors/john-doe
data() params:  {}
```

**Comment by tony-navillus** [comment]
Note: Just tried replacing my entire `$authors` route with the [docs example](https://github.com/snowpackjs/astro/blob/main/docs/collections.md#example-individual-pages-from-a-collection) and hit the same issue in `data()`

**Comment by tony-sull** [comment]
Had a chance to do some debugging on this one.  I haven't totally nailed down the issue, but it may end up being a misuse of the collections API

What I'm attempting to build is:
- `src/pages/$authors.astro` page that compiles to `/authors/index.html` or similar.  This page will act as an index listing each author found after scrubbing each blog post
- `src/pages/$author.astro` which compiles to an individual page along the lines of `/authors/author-one/index.html`.  Each page will be a filtered list of post previews written by that author

Best I can tell, `runtime.ts` is assuming that the `$author.astro` component is can be called for routes `/author` as well as `/author/author-one`.  I'm hitting an error because `runtime` tries to call `data({ params })` with the params for a `/author` route, but that route shouldn't exist and doesn't get any data.

It looks like the `runtime` logic is mixing the use case of pagination and individual pages per item, but I haven't had a chance yet to find the best way to untangle the two.

---
Ran out of time for the night but hopefully this is useful in case anyone picks up this bug before I get back to it!

**Comment by FredKSchott** [comment]
Oh, this is a bug: Collections `data()` currently needs to return an array. If you make this change, it appears to work:

```
        async data ({ params }) {
            console.log('data() params: ', params);
-            return allAuthors[params.index];
+            return [allAuthors[params.index]];
+             // then, grab from `collection.data[0]` in your template
        },
```

**Comment by FredKSchott** [comment]
also @tony-navillus in the example repo:
- I think you meant to do `import Layout from '../layouts/Base.astro';` in `$authors.astro`
- `$author` set the permalink `/authors/` which was really tricky to debug. Comment for @snowpackjs/maintainers : I think we need to prevent permalinks from escaping their name and save users from this footgun (`$foo.astro` should only be able to create `/foo/*` permalinks).

**Comment by tony-navillus** [comment]
I just pushed an update the to my demo repo that *mostly* fixes this.  After better understanding the difference between `params` and `data`, I realized that I'm better off following the [Grouping content by tag, author, etc](https://github.com/snowpackjs/astro/blob/main/docs/collections.md#example-grouping-content-by-tag-author-etc) docs example.

Interestingly, after fixing the `$author.astro` template so that it renders a page for each author, I lost the `/authors` route?  It seems like `$author` is somehow shadowing `$authors`, if I rename it to `$people.astro` to avoid name collisions the page starts rendering again 🤔

> I think you meant to do import Layout from '../layouts/Base.astro'; in $authors.astro
Yep, looks like that was an issue for me too.  I was actually expecting `Page.astro` to be able to pick up props exported from `.astro` frontmatter similar to markdown but that didn't work.  Guess I really should rename that layout to `MarkdownPage` or similar

> $author set the permalink /authors/ which was really tricky to debug. Comment for @snowpackjs/maintainers : I think we need to prevent permalinks from escaping their name and save users from this footgun ($foo.astro should only be able to create /foo/* permalinks).
Is it possible to have routes similar to `/authors` and `/authors/jane-doe`?  Or is that just not supported?  I guess I may be able to overload the `$authors.astro` file to render both the index file as well as the author-specific pages, but that could get nasty with larger templates

> The issue appears to be when you set pageSize: Infinity.
Yep that's definitely part of what I ran into.  I actually think it's not totally crazy, in a real blog the `/author/:slug` routes really should still support pagination in case any author has a huge list of posts.

**Comment by tony-navillus** [comment]
PR submitted: https://github.com/snowpackjs/astro/pull/516

**Comment by wobsoriano** [comment]
Updated to the latest version and still seeing empty data error. I have 2 routes

1. $characters.astro
2. $character.astro

`/character/1` works but `/characters/1` returns `Error: [createCollection] data() returned nothing (empty data)"`

**Comment by tony-navillus** [comment]
@wobsoriano Yep I realized I am still hitting thst as well.  I filed #532 earlier to track that issue separately
